### ISSUE TITLE
Work Experience

### ISSUE THREAD

**Issue by RodrigoLaraM** [MLH-Fellowship/project-dancing-ducks#3]
Add your previous work experiences

**Comment by gujiguj** [comment]
Since this will be on the same page as the "About yourself" and "Education," I'm going to move this to the ["About yourself" issue. ](https://github.com/MLH-Fellowship/project-dancing-ducks/issues/2)

**Comment by gujiguj** [comment]
(didn't mean to close it! I'm keeping it open under the "About yourself" issue.)
