### ISSUE TITLE
Education

### ISSUE THREAD

**Issue by RodrigoLaraM** [MLH-Fellowship/project-dancing-ducks#5]
Add your current/previous education

**Comment by gujiguj** [comment]
Since this will be on the same page as the "About yourself" and "Work Experiences," I'm going to move this to the ["About yourself" issue. ](https://github.com/MLH-Fellowship/project-dancing-ducks/issues/2)

**Comment by gujiguj** [comment]
(didn't mean to close it! I'm keeping it open under the "About yourself" issue.)
